---
title: "Temp"
author: "Smitesh Patil"
date: "2023-03-20"
output: html_document
---

```{r}
g<- read_graph(file="./WordPairs.txt",format="pajek")
g<- as.undirected(g)
g<- simplify(g)

cues <- read.table("./cue.txt", header = F, sep="\t", skip=4)

V(g)$cue<-cues[[1]]

#checking the diameter value
print(diameter(g, weights = NA))


```

```{r}

page_rank_network <- function(g, target_node_names, topn, damping){
  
  teleport_probs <- rep(0,vcount(g))
  teleport_probs[as.numeric(V(g)[target_node_names])]<-1/length(target_node_names)
    
  
  pr<- page_rank(g,  directed = F, personalized=teleport_probs, damping = damping)$vector
  
  top_n_pr <- order(pr, decreasing=TRUE)[1:topn]
  top_n_pr<-V(g)[top_n_pr]
  
  return(top_n_pr)
}

page_rank_network(g, c("HEAD", "HEART"), 160, 0.85)

```


```{r}

library(igraph)

# start with a clique
g <- graph.full(5)
for (i in 0:5) {
  # add another clique
  g <- g %du% graph.full(5)
  # then add some edges between cliques
  g <- add.edges(g,c(5*i+1,5*(i+1)+1))
  g <- add.edges(g,c(5*i+2,5*(i+1)+2))
}
g <-add_edges(g, c(33,3, 34,4))


v2 <-9
v1 <-35

topic<-c(v1,v2)

# initial vector of zeros
teleport_probs <- rep(0,vcount(g))
# we set the probability of returning to the topic node 
teleport_probs[as.numeric(V(g)[topic])]<-1/length(topic)

pr<- page_rank(g,  directed = F, 
               personalized=teleport_probs, 
               damping = 0.85)$vector

n <-10
#the vertex ids of the top n scores
top_n_pr <- order(pr, decreasing=TRUE)[1:n]

#the top n vertices
top_n_pr<-V(g)[top_n_pr]

```
