---
author: "Smitesh Patil"
date: "2023-03-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# This code provides and example of how to 
# read the .shp file provided for this assignment.
# It also provides an example of the normalisation of 
# the daily and cumulative case figures per 100,000 of population of each county
# for one date.

library(sf)
library(dplyr)

# sr_read will read the data in the shp file into a dataframe
# However, it also requires the other files in the zip file you downloaded.
# If you are getting a read error, make sure that the other files
# .dbf, .prj and .shx are in the same folder as the .shp file you are 
#  attempting to read

IRL_counties_Covid19 <- st_read("C:\\Users\\Smitesh\\Documents\\Football Data Analysis\\Data\\Data Visualization\\Assignment 2\\CovidCountyStatisticsIreland_v2.shp", quiet = TRUE)

# This is an example of calculating the number cumulative and daily cases per county 
# normalized by 100,000 of population as at 01 September 2021. 

# lubridate is useful library for manipulating and comparing date values
library(lubridate)

IRL_Covid19_2021_09_01<- IRL_counties_Covid19%>%
  filter(TimeStamp == ymd("2021-12-21"))%>%
  mutate(ConfirmedC_per_100k =  round(100000  * ConfirmedC/Population,1))%>%
  mutate(DailyCCase_per_100k =  round(100000  * DailyCCase/Population, 1))

```

```{r}
library(ggplot2)
library(colorspace)
library(colorblindr)

ggplot(IRL_Covid19_2021_09_01, aes(x = ConfirmedC_per_100k, y = reorder(CountyName, ConfirmedC_per_100k)))+
  geom_bar(stat = "identity")
```

```{r}
mean_daily_cases <- IRL_Covid19_2021_09_01 %>%
  select(ConfirmedC_per_100k) %>%
  st_drop_geometry() %>% 
  unlist() %>% 
  mean()

IRL_Covid19_2021_09_01<- IRL_Covid19_2021_09_01 %>%
  mutate(mean_divergence =   - mean_daily_cases) 

plt_order <- order(IRL_Covid19_2021_09_01$ConfirmedC_per_100k, decreasing = TRUE)
IRL_Covid19_2021_09_01$mean_divergence = factor(IRL_Covid19_2021_09_01$ConfirmedC_per_100k, 
                                                levels = IRL_Covid19_2021_09_01$ConfirmedC_per_100k[plt_order])

```

```{r}
library(colorspace)
library(ggridges)

IRL_Covid19_plot3<- IRL_counties_Covid19%>%
  filter(CountyName == "Galway") %>%
  filter(TimeStamp %in% seq(ymd("2021-08-01") , ymd("2021-12-01"), by="weeks"))


ggplot(IRL_Covid19_plot3, aes(x= TimeStamp, y= DailyCCase)) +
  geom_point()+
  geom_smooth(se= FALSE, color = "blue")

  
```


```{r}

mean <- IRL_counties_Covid19 %>%
  st_drop_geometry() %>%
  mutate(ConfirmedC_per_100k =  round(100000  * ConfirmedC/Population,1))%>%
  mutate(DailyCCase_per_100k =  round(100000  * DailyCCase/Population, 1))%>%
  select(CountyName, DailyCCase_per_100k) %>%
  group_by(CountyName) %>%
  summarise(mean = mean(DailyCCase_per_100k, na.rm = TRUE)) %>%
  arrange(desc(mean))

plt_data<- IRL_counties_Covid19%>%
  mutate(ConfirmedC_per_100k =  round(100000  * ConfirmedC/Population,1))%>%
  mutate(DailyCCase_per_100k =  round(100000  * DailyCCase/Population, 1))%>%
  filter(CountyName %in% c("Galway", head(mean$CountyName, 1), tail(mean$CountyName, 1)))

plt_data2<- IRL_counties_Covid19%>%
  mutate(ConfirmedC_per_100k =  round(100000  * ConfirmedC/Population,1))%>%
  mutate(DailyCCase_per_100k =  round(100000  * DailyCCase/Population, 1))%>%
  filter(!CountyName %in% c("Galway", head(mean$CountyName, 1), tail(mean$CountyName, 1)))
  


ggplot(plt_data, aes(y=ConfirmedC_per_100k, x = TimeStamp, ))+
  geom_smooth(data = plt_data2,aes(group = CountyName, colour = "#d3d3d3" ), size = 0.1, alpha = 0.9, na.rm = TRUE, method = "loess", se = FALSE)+
  geom_smooth(data = plt_data, aes(group = CountyName, color = CountyName), size = 1.5, alpha = 0.8, na.rm = TRUE, method = "loess", se = FALSE)+
  scale_color_manual(values = c("#d3d3d3", "#663399", "#339999", "#000066"), labels = c("Others", "Galway", "Monaghan", "Wicklow"))
  
```
Part 5
```{r}
part_5 <- IRL_counties_Covid19%>%
  mutate(ConfirmedC_per_100k =  round(100000  * ConfirmedC/Population,1))%>%
  mutate(DailyCCase_per_100k =  round(100000  * DailyCCase/Population, 1))

part_5 <- part_5[part_5$TimeStamp >= ymd("2021-01-01") & part_5$TimeStamp <= ymd("2021-02-01"), ]

part_5 <- part_5 %>% group_by(CountyName) %>%
  summarise(Cumulative_DailyCCases_per_100k_4Weeks = sum(DailyCCase_per_100k))

part_5 <- part_5 %>% 
  select(CountyName , Cumulative_DailyCCases_per_100k_4Weeks) %>%
  mutate(mean_4weeks = mean(Cumulative_DailyCCases_per_100k_4Weeks))

part_5<- part_5 %>%
  mutate(mean_divergence =  Cumulative_DailyCCases_per_100k_4Weeks - mean_4weeks)

ggplot(part_5) +
  geom_sf(aes(fill = -mean_divergence)) 

```