---
title: "Assingment 2 Main"
author: "Smitesh Patil"
date: "2023-03-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(dplyr)
library(ggplot2)
library(lubridate)
library(colorblindr)
IRL_counties_Covid19 <- st_read("C:\\Users\\Smitesh\\Documents\\Football Data Analysis\\Data\\Data Visualization\\Assignment 2\\CovidCountyStatisticsIreland_v2.shp", quiet = TRUE)

```

```{r}
palette <- colorblindr::palette_OkabeIto

IRL_Covid19_2021_12_21<- IRL_counties_Covid19%>%
  filter(TimeStamp == ymd("2021-12-21"))%>%
  mutate(ConfirmedC_per_100k =  round(100000  * ConfirmedC/Population,1))%>%
  mutate(DailyCCase_per_100k =  round(100000  * DailyCCase/Population, 1))

mean_daily_cases <- IRL_Covid19_2021_12_21 %>%
  select(ConfirmedC_per_100k) %>%
  st_drop_geometry() %>% 
  unlist() %>% 
  mean()

IRL_Covid19_2021_12_21 %>% 
  mutate(color = ifelse(CountyName == "Galway", "1", 
                        ifelse(ConfirmedC_per_100k < mean_daily_cases, "2", "3"))) %>%
  ggplot(aes(x = ConfirmedC_per_100k, y = reorder(CountyName,ConfirmedC_per_100k)))+
  geom_point(size = 2, aes(color = color))+
  geom_vline(aes(xintercept = mean_daily_cases))+
  geom_linerange(aes(xmin = mean_daily_cases, xmax = ConfirmedC_per_100k, color = color),
                 linetype = "dashed")+
  scale_color_manual(values = c(palette[2], palette[1], palette[5]),
                    labels = c("Galway", "Counties performing better than average",
                               "Counties performing worse than average"))+
  scale_x_continuous(limits = c(10000, 19000),
                     breaks = seq(10000, 19000, by = 1000),
                     name = "Confirmed Cases (Per 100,000 people) -->")+
  scale_y_discrete(name = "Counties -->")+
  annotate(x=mean_daily_cases+900, y=1, label="<- mean line", color="black", geom = "text",
           lineheight = .6)+
  theme_minimal()+
  theme(legend.position = "top",
        legend.title = element_blank())
```

```{r}
IRL_Covid19_plot2 <- IRL_counties_Covid19%>%
  mutate(ConfirmedC_per_100k =  round(100000  * ConfirmedC/Population,1))%>%
  mutate(DailyCCase_per_100k =  round(100000  * DailyCCase/Population, 1))
  
mean <- IRL_counties_Covid19 %>%
  st_drop_geometry() %>%
  mutate(ConfirmedC_per_100k =  round(100000  * ConfirmedC/Population,1))%>%
  mutate(DailyCCase_per_100k =  round(100000  * DailyCCase/Population, 1))%>%
  select(CountyName, DailyCCase_per_100k) %>%
  group_by(CountyName) %>%
  summarise(mean = mean(DailyCCase_per_100k, na.rm = TRUE)) %>%
  arrange(desc(mean))

max <- IRL_Covid19_plot2 %>%
  st_drop_geometry() %>%
  select(CountyName, ConfirmedC_per_100k) %>%
  group_by(CountyName) %>%
  summarise(max = max(ConfirmedC_per_100k), min = min(ConfirmedC_per_100k))

select_county_data<- IRL_counties_Covid19%>%
  mutate(ConfirmedC_per_100k =  round(100000  * ConfirmedC/Population,1))%>%
  mutate(DailyCCase_per_100k =  round(100000  * DailyCCase/Population, 1))%>%
  filter(CountyName %in% c("Galway", head(mean$CountyName, 1), tail(mean$CountyName, 1)))

other_counties<- IRL_counties_Covid19%>%
  mutate(ConfirmedC_per_100k =  round(100000  * ConfirmedC/Population,1))%>%
  mutate(DailyCCase_per_100k =  round(100000  * DailyCCase/Population, 1))%>%
  filter(!CountyName %in% c("Galway", head(mean$CountyName, 1), tail(mean$CountyName, 1)))

IRL_Covid19_plot2 %>%
  ggplot(aes(x = TimeStamp, y=ConfirmedC_per_100k, color = color))+
  geom_smooth(data = other_counties,aes(group = CountyName, colour = "#d3d3d3" ), size = 0.1, alpha = 0.9, na.rm = TRUE, method = "loess", se = FALSE)+
  geom_smooth(data = select_county_data, aes(group = CountyName, color = CountyName), size = 1, alpha = 0.8, na.rm = TRUE, method = "loess", se = FALSE)+
  scale_color_manual(values = c("#d3d3d3", palette[3],palette[6] , palette[4]), labels = c("Others", "Galway", "Monaghan", "Wicklow"))+
  scale_y_continuous(limits = c(0, 19000),
                     breaks = seq(0, 19000, by = 2000),
                     name = "Confirmed Cases (Per 100,000 people) -->")+
  scale_x_date(date_breaks = "months", date_labels = "%b-%y", 
               name = "Time -->")+
  theme(axis.text.x = element_text(angle = 50, vjust = 0.5, hjust=1),
        axis.title.x = element_text(vjust = -2.5),
        legend.position = "top",
        legend.title = element_blank())

  
```

