library(dplyr)
library(tidyr)
library(kableExtra)
data <- tibble(number = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                          11, 12, 13, 14, 15, 16, 17, 18, 19),
                   paper = c("Goyal et al", "Goyal et al", "Goyal et al",
                             "Elshennawy et al", "Elshennawy et al",
                             "Elshennawy et al", "Elshennawy et al",
                             "Rahman et al", "Rahman et al",
                             "Rahman et al", "Rahman et al",
                             "Rahman et al", "Rahman et al",
                             "Rahman et al", "Rahman et al",
                             "Rahman et al", "Rahman et al",
                             "Rahman et al", "Rahman et al"),
                   classifier = c("F-RNN-LSTM", "F-RNN-LSTM", "F-RNN-LSTM",
                                  "ResNet152V2", "MobileNetV2", "CNN", "LSTM-CNN",
                                  "AlexNet", "ResNet18", "DenseNet201", "SqueezNet",
                                  "AlexNet", "ResNet18", "DenseNet201", "SqueezNet",
                                  "AlexNet", "ResNet18", "DenseNet201", "SqueezNet"),
                   data = c("Raw features", "Min-Max-Normalised", "Robust Normalisation",
                            "5856 images (1583 normal, 4273 pneumonia)",
                            "5856 images (1583 normal, 4273 pneumonia)",
                            "5856 images (1583 normal, 4273 pneumonia)",
                            "5856 images (1583 normal, 4273 pneumonia)",
                            "Normal and Pneumonia", "Normal and Pneumonia", 
                            "Normal and Pneumonia", "Normal and Pneumonia",
                            "Normal, Baterical Pneumonia and Viral Pneumonia",
                            "Normal, Baterical Pneumonia and Viral Pneumonia",
                            "Normal, Baterical Pneumonia and Viral Pneumonia",
                            "Normal, Baterical Pneumonia and Viral Pneumonia",
                            "Bacterial and Viral Pneumonia", "Bacterial and Viral Pneumonia",
                            "Bacterial and Viral Pneumonia", "Bacterial and Viral Pneumonia",
                            ),
                   accuracy = c("89.36", "93.55", "95.04", "99.22", "96.48", "92.19",
                                "91.80", "94.5", "96.4", "98.0", "96.1", "88.4",
                                "87.7", "93.3", "86.1", "90.0", "87.0", "95.0","83.0"),
                  f1 = c("90.22", "94.00", "95.19", "99.44", "97.52", "93.79",
                         "92.29", "94.3", "96.5", "98.1", "96.1", "88.5", "90.9",
                         "93.5", "86.5", "92.1", "87.3", "95.2", "84.0"),
                  AUC = c("-", "-", "-",
                          "99.77", "97.59", "96.92", "95.49",
                          "94.2", "96.3", "98.0", "96.0",
                          "91.1", "91.0", "95.0", "89.5",
                          "89.0", "87.0", "95.2", "83.0"))
                   

data <- kbl(data, format = "latex")
